#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AdMobExamples.Resource", IsApplication=true)]

namespace AdMobExamples
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int adSize = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int adSizes = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int adUnitId = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Splash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int adjust_height = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int adjust_width = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int none = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f040000
			public const int google_play_services_version = 2130968576;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f03000a
			public const int ApplicationName = 2130903050;
			
			// aapt resource value: 0x7f030009
			public const int Hello = 2130903049;
			
			// aapt resource value: 0x7f030005
			public const int accept = 2130903045;
			
			// aapt resource value: 0x7f030001
			public const int auth_google_play_services_client_facebook_display_name = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int auth_google_play_services_client_google_display_name = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int common_google_play_services_unknown_issue = 2130903042;
			
			// aapt resource value: 0x7f030008
			public const int create_calendar_message = 2130903048;
			
			// aapt resource value: 0x7f030007
			public const int create_calendar_title = 2130903047;
			
			// aapt resource value: 0x7f030006
			public const int decline = 2130903046;
			
			// aapt resource value: 0x7f030004
			public const int store_picture_message = 2130903044;
			
			// aapt resource value: 0x7f030003
			public const int store_picture_title = 2130903043;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_IAPTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Theme_Splash = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
